// See https://aka.ms/new-console-template for more information


using Template;

const string inputReal = @"YYYYYYYYYEJJEEEEEEEEEEEEEEGGGGGGGGGGGGGGGGGGCCCCCCCCCCWWCCLLLKKKKJKKKKKKFFFFFFFBBBBBBBBBBBAEEEEEEEEEEEEPPPPPPPPPOOOOZYYYZZZZZZAAUUUUUUUUUUUU
YYYYYYYYNEEEEEEEEEEEEEEEEEGGGGGGGGGGGGGGGGGCCCCCCCCCCCCCCCLLLLKKKKKKKKKKKFFFFFBBFBOBBBBBBBBBEEEEEEEEEEEPPPPPPOOOOOOOZZZZZZZZZZZAAUKUUUUUUUUU
YYYYYYNNNNYEEEEEEEEEEEEEEEGGGGGGGGGGGGGGGGGGCCCCCCCCCCCCCCCCLKKKKKKKKKKKKFFFFFFFFBBBBBBBBBBBBEEEEEEEEPPPPPPPOOOOOOOOOZZZZZZZZZUUUUUUUUUUUUUU
YYYNNNNNNNEEEEEEEEEEEEEEEEEGGGGGGGGGGGGGGGVVVVCCCCCCCCCRREEEEKKKKKKKKKKKKFFFFFFXFBBBBBBMMBBBBBEEEEEFEPPPPPPOOOOOOOOOOOZZZZZZZZZZUUUUUUUUUUUU
YYYNNNNNNWWEEEEEEEEEEEEEEEEGGGGGGGGGGGGGGGWVVVVVCCCCCCRRREEMEEKKKKKKKKKKKFFFFFXXFFBBBMBMMEEEEEEEEEEEPPPPPPPOOOOOOOOOOOZZZZZZZZZUUUUUUUUUUUUU
YYNNNNNNNNEEEEEEEEEEEEEEEEEEIIIIGGGGGGGGGWWWVVVVVCCCCCCEEEEMEKKKKKKKKKKKKKFFFFXXXBBBMMMMMEEEEEEEEEEEPPPPPPPPOOOOOOOOOOOOZZZZUUZUUUUUUUUUUUUU
YNNNNNNNNNNEEEEEEEEEEEEEEEEEIIIIGGGGGGGWWWWVVVVWWWWCWCCWEEMMMKKKKKKKKKKKKKFFFFXXXXXXMMMMEEEEEEEEEEEPPPPHHHHPPOOOOOOOOOOOZZZUUUUUUUUUUUUUUUUN
NNNNNNNNNNNNEEKEEKKKVEEEEEEIIIIIGIGGVGGGWCWWWWVVVWWWWCWWMMMMKKKKKKKKKKKKKKXXXXXXXXXXMMMMMEEEEEEEEEEPPHHHHHHPPOOOOOOOOOOOZZZUUUUUUUUUUUUUUUUN
NNNNNNNNNNNNAKKKKKKKKEEEEEEIIIIIIIGVVGGGWCCWWWWWWWWWWWWWWMMMMMMBBBKKKKBKKKBBXXXXXXXXMMXMMMEMMEEEEEQCPCHHHHHHPPOOOVVVOOOOZOOOOUUUUUUUUUUUUUNN
JJNNNNNNNNNNNKKKKKKKKEEEETTTTTTTTTGGGGGGCCCWWWWMWMMWWWWWWWMMMMMMMBBBKBBBKBBBBXXXXXXXXXXMMMMMMEEEQQQCCCHHHHHHHPVOOVVVOVOOOOOOOOOUUUUUUUUUUNNN
JJNNJNNNNNNJKKKKKKKKKKEEETTTTTTTTTTTIGGGCCCCWWWMMMMMWWWWWWWWWWMMKVBBBBNBBBBBBXXXXXXXXXXMMMMMMEEQQYQCCCHHHHHHHVVOOVVVVVOOOOOOOOOOUUQQUUUUNNNN
JJNNJNNNJJJJJKKKKKKKKKKKZTTTTTTTTTTTTTCGCCCCWWWMMMMMWWWWWWWWWWMVKVBBBNNNNBBBBXXXXXXBXNMMMMMMMMHQQQQCCCCHHHHHVVVHVVVVVVVVOOOFFFOOQQQQUNNNNNNN
JJJJJNNNJJJJJJKKKKKKKKKZZTTTTTTTTTTTTTCCCCCCCWMMMMWWWWWWWVWWVVVVVVBBBNXNNNNBBBBXXBBBMMMMMMMMMQQQQQQCCCCHHHHHHVVHVVVVVVVVOFFFFFOOQQQQUQNNNNNN
JJJJJNIJJJJJKKKKKKKKKKKKZZZZITTTTTTTTTCCCCCCCCMMMMWWWWWWVVVVVVVVVVVBVNNNNNNNBBBBXBBBBBMMMMMMMKQQQQQQCQCHHHHHHVVVVVVVVVVVVFFFFFOQQQQQQQQNNNNN
JJJJJJJJJJJJJKKKKKKKKKKKZLZZZTTTTTTTTTCCCCCCCCMMMMMMMWVWVVVVVVVVVVVVVNNNNNNNBBBBXBBBBBMMMMMMMQQQQQQQQQHHHHHMHHZVVVVVVVVVVVFFQOOOQQQQQQNNNNNN
JJJJJJJJJJCCCKVKKKKKKKZZZLLLLZZCTTTTCCCCCCCCCCMMMMMMMMVVVVVVVVVVVVVVNNNNNNRRRRRBBBBBMMRRRMMMMMQQQQQQQQMMMXMMMHVVVVVVVVVVVVQQQQQOOOQQQQNNNNNN
JJJJJJJJJJCCCCKKKKKKKZZZLLLLCCCCTTTTTTTTTCCLLMMMMMMMMMTVVVVVVVVVVVVVNNNNNNRRRRRRRBBBMMMMRMMMMQQQQQQQQQMMMMMMMEMVVVVVVVVVVVQQQHQQQQQQQQNNNNNN
JJJJJJJJJJCCCCIKKKKKKZLLLLLDLCCCTTTTTTTTTCLLLMMMMMMMMTTTTVVVVVVVVVVVNNNNNNNRRRRRRRBBMMMMMMMMQQQQQQQQQQMMMMMMMMMMVVVVVVVVVVVVQHHHQQQQNNNNNNNN
JJJJJJJJJCCCCCIKKKKKZZLLLLLLLCCCTTTTTTTTTCCLLLLLMMMEMTTTIIIIVVVVVVVVNNNNNNNNRRRRRRRRMMMMMMMMMQQQQQQQQMMMMMMMMMMMVVVVVVVVVVVVQHHHHQQQQNNNNNNN
JJJJJJDJCCCCCCCCKKKKKCLLLLLLLCCCTTTTTTTTTLLLLLLEEMMEITIIIIIIIIIVVVVVNNNNNNNRRRRRRRRJJJMMMMMMMBBQQQQQQMMMMMMMMMVVVVVVVVVVZIHHHHHHHQQQNNKKNNNN
JJJJJJDJCCCCCCCCCCCCCCLLLLSLLZZZZZTTTTTTTLLLLLLLEEEEIIIIIIIIIIIEVVNNNNNNNNRRRRRRRRRRMMMMMMMMBBBQBPQQQMMMMMMMMMVVVVVZVVVVZIHHHHHHHHHNNNNNNNNN
DJJJDDDCCCCCCCCCCCCCCLLLLLSSSZZZZZTTTTTTTLLLLLLLLEEIIIIIIIIIIIIIINNNNNNNNNRRRRRRRRRRMMMMMMMMMBBBBBBMMMMMMMMMMMVVVVVZZZVVZIIIIHHHHHHNNNNNNNNN
DDDJDDCCCCCCCCCCCCCCCLLLLLLSSZZZZZTTTTTTTLLLLLLIEEIIIIIIIIIIIIIIIINNNNNNNCNRRRRRRQQRMMMMMMMMMBBBBBBMMMMMMMMMMMMVVVVZZZZZZIIIIHHHHHHNNNNNNNNN
DDDDDDCCCCCCCCCCCCCCCLLLLSSSSZZZZZTTTTTTTLLLLLLIIIIIIIIIIIIIIIIIPIPNNCNNNCCCCRRRRRMMMMMMMMMMMBBBBBBMMMMMMMMMMMVVVVVZZZZZZIIIHHHHCNNNNNNNNNNN
IDDDDDCCCCCCCCCCCCCCLLNNLSSWSSZZZZTTTTTTTLLLLLIIIIIIIIIIQIQFQQIPPPPPPCNCCCCGCRRRMMMMMMMMMMMMBBBBBBBBBBMMMMMMMMMMMZZZZZZZZIIIHHHHHCNNNNNNNNNN
IIIDDIIYCCCCCCCCCCCLLLLNNSSWWWWZWWWEELLLLLLLLLIIIIIIIIIIQQQQQQPPPPPPCCCCCCCCCRRMMMMMMMMMMMMMBTBBBBBBBBMMMMMMMMMBBBZZZZZZZZIHHHNNNNNNNNNNNNNN
IIIDIIIICCCCCCCCLLLLLLLNNSSWWWWWWWWEEEEELLLLLIIDDDIIIIQQQQQQQQQPPPPPCCCCCCCCCRMMMMMMMMMMMMMMBBBBBBBBZZTMMMMMMMBBBBBBZZZZZZZNNNNNNNNNNNNNNNNN
IIIIIIIIIKCKCCCCXLLLLLNNNSSWWWWWWEEEEEEELLLLLIIDDDIIIQQQQQQQQQPPPPPPPPPCCCCCCRMMMMMMMMMMCCCMTBBBBBZZZZZPMMMMKMBBBBBBZZZCZZZNNNNNNNNNNNNNNNXX
IIIIIIIIIKCCCCCCXLLLLLNNNNNWWWWWWWEEEEELLELLLAIDDDDDDQQQQQQPPPPPPPPPPCCCCCCCCCCCMMMMMMMMMMMMMWBBBZZZZZLLLMMKKSBBSBBBZZZXZZZNNNNNNNNNNNNNNNXX
IIIIIIIIIXCCCCXXXXXLLLNNNYNVWWWWWEEEEEELEELLLLDDDDDDDQQQQQQPPPPPPPPPCCCCCCCCCCCCCMMMMMMMMMMMMWWZZZZZZZZLLULLKSSSSBSBXNNXXRXXNNNNNNNNNNNXXXXX
IIIIIIIIIXXCCXXXXXXXNNNNNYNVBBBWWBEEEEEEELLDDDDDDDDDDQQQQQQQQQPPPPPPPCCCCCCCCCCCCMMMMFFMMMMNMZZZZZZZZZLLLULLKSSSSSSXXXNXXXXXXNNNNNNNNNNXXXXX
IIIIIIIXXXXXXXXXXXNAANNNNYNNBBBBBBBEJJEAEDDDDDDDDDQQQQQQQQQQPQPPPPPPPCCCCCCCCCCCTFFFFFFFMMMMMMMUZZZZZZLLLLLLLSSSSSSSXXXXXXXNNNNNNNNNNNNXXXXX
IIIIIIIXXXXXXXXXXXNAANNNNNNNBBBBBBBJJJDDEDDDDDDDBBIIIQQQQQQQPPPPPPPCCCCCCCCCCCCUFYFFFFFNFMMMMEUUZZZZZAALLLLLLSSSSSSXXXXXXXXNNNNNNNNNNGGGXXXX
IIIIIIIIIXXXXXXXXNNNNNNNNNDNBBBBBBBBJJDDDDDDDDDBBIIIQQQQQQQQPQPPRPPCCCCCCCCCCCCFFFFFFFFFFFFMEEUUZZQZQLLLLQSSLSSSSSSSXXXXXXXNNNNNNNNGGVGGGXXX
IIIIIIIXXXXXXXXXXXXNNNNNNDDDBBBBBBBJJJDDDDDDDBBBBBBBQQQQQQQQQQPCRRRCCCCCCCCCCYYYYFFFFFFFFFFUUUUUUZQQQLLLLQSSSSSSSSSSXXXXXXNNNNNNNNNGGGGGXXGG
IIIIIIIIXXXXXXXXXXXNNNNNDDBBBBBBBBBBBDDDDDDDBBBBBBBBQQQQQQQQQQPCRRCCCCCCCCCCCYYYFFFFFFFFFFTTUUUUUQQQQQQLLQQQSSSSSSSXXXXXXXXNNNNNNNNGGGGGGGGG
IIIIIIXXXXXXXXXXXXXXNNNNDDBBBBBBBBBJJDDDDDDDBBBBBBBBBBQQQQQQCCCCCRCCCCCCCCCYYYYYYYFFFFFFFZTTTUUUQQQQQQQQQQQQQSSSSSXXXXXXXXNNNNNNNNNNGGGGGGGG
IIIIIIIXXXXXXXXXXXXNNNNNNNNVVBBBBBBJJJJDDDDDBBBBBBBBBBBQQQQQQQCCCCCCCCCYCCYYYYYYYYYFFFFFFZTTTZQQQQQQQSSSQQQQSSSSSSXXXXXXXXXNNNNNNGGGOGGGGGGG
IIINNNNZCXCXXCCXXXXNNNNVVVVVVBBBJJBBJJJDDKDKBBBBBBBTTBBQQQUQQQCCCCCCCYYYYCYYYYYYYYYFFFZZZZZZZZZQQQQSSSSSQQQQQQXXXXXXXXXXXXXNNNNNNGGGGGGGGGGG
NNNNNNNZCCCXCCXXXXXXNNNOVVVVVBBBJJBBJJJJDKKKBBFTTTTTTBBQQQQQQCCCCCCCCYYYYYYYYYYYYYYZQQZZZZZZZZZZSSSSSSSSQSQQQQXXXXXXXXXXKXXNNNNNNNGGGGGGGGGG
CCNNNNNNCCCCCXXXXFFXXNOOOOOVOOBBJJJJJJJJDKKKKKFFTTUTTBTQHQQHQCCCCCCCHYYYYYYYYYYYYZYZZZZZZZZZZZZZSSSSSSSSSSQQXXXXXXXXKXXKKKXNNNNNNNGGGGGGGGGG
CCCCNNNCCCCCXXXXFFFXXXOOOOOVOOJJJJJJJJJJKKKKKKFFFFFFFTTHHQHHQCCCCCCCHYYYYYYYYYYYYZZZZZZZZZZZZZZZSSSHSSSSSSSSFXXXXXXXKKKKKKKNNNNNNNNGGGGGGGGG
CCCCCCNCCCRCXXFXFFFOOOOOOOOOOOJAAAAAAJKKKKKKTTFFFFFFFTTHHHHHCCCCCCCCCYYYYYYYYYYYYYZZZZZZZZZZZZZZSSSSSSSSSSSSFFXXXSXXKKKKKKKNNNNNNNGGGGGGGGGY
CCCCCCCCCCRCCXFFFFFFFOOOOOOOOOOOAAAAAKKKKFFFFFFFFFFFFTTHHHHHHCCCHCCHHHQQYYYYYYYZZZZZZZEEEEEEEZZZZZZSSSSSSSSFFFSXSSXXKKKKKKKKKNNNNNNGGGGGGGGY
CCCCPCCCCCCXXXFFFFFFFOOOOOOOOOOOOAAAKKKKKFFFFFFFFFFFFTTTHHHHHCCCHCHHHHHQQYYYYYYYYYZHZZEEEEEEEZZZZSSSSSSSSSSSSFSSCSXHKKKKKKKKNNNNCCNGGGGGGGGG
CCCCCCCCCCCCXXFFFFTTFOOOOOOOOOOOAAAKKKKKKFFFFFFFTTTTTTTTHHHHHHHHHHHHHHHQQYYYYYYYYYZZZEEEEEEEEEZZZSSSSSSSSSSOSSSSSSSHHHKKKKKKKNCCCCJGGGLGGGGG
SCMMMCCCCCCVVFFFFFFTOOOOOOOOOOAAAAAKKKKKKFFFFFFFTTTTTTTTHHHHHHHHHHHHHHQQRRYYYYYBYYZEEEEEEEEEEEZZZSSSSSSSSSSOSSSSSSSSSKKKKKKRKKKSCCCCCLLLGGLL
SCMMMMMTCTTTTTTFFFTTOOOOOOOOOOAAAAAKKKKKKFFFFFFFTTTTTTTHHHHHHHHXHHHNNNQQRRRRUNNBYMMEEEEEEEEEEEZCCCCCSSSSSSSOSSSSSSSSKKKKKKKRKKKCCCCXCLLLLLLI
SSITMTTTTHTTTTTEETTTOOOOOOIOAAAAAAKKKKKKKFFFFFFFTTTUTTTTHHHHHHHHHHHHNNNRRRREEEEEEEEEEEEEEEEEEECCCCSSSSSSTSSSSSSSSSSSSKQQKKKKKSSCXCCJLLLLLLLL
IIITTTTTTTTTTTTTTTTOOOOOOOOOAQAQQAKKKKKKKKKKKKKTTKUUDTTTTHUHSHHHHHHNNNRRRRREEEEEEEEEEEEEEEEEESSCCEEESSSSTTSSSSSSSSSSSSSSCKEEJJJJJJJJULLLLLUU
IIIIMTTTTTTTTTTTTTTCOOXXOOOOQQAQQKKKKKKKKKKKKKKKKKUUDTTTUUUEUMMHHHHHNPRRRRREEEEEEEEEEEEEEEEEEISCCEEEESMMSSSSSSSSSSSSSSSSJJJEJJJJJJJJULLLLUUU
IIIIMMTTTTTTTTTTTTDOOOXXOOOPQQQQQQYYYNKKKKKKKNNKKKUUUUUUUUUUUMMHHHHPPPRRPRREEEEEEEEEEEEEESSSSSSCCEEEEEEESSSSSSSSSSSSSSSJJJJJJJJJJJJUUUUUUUUU
IIIMMMTRTTTTTTTTTTTEOOOOOOOIQQQQQQYYYNNNNNNNKNNKKKUUUUUUUHUUUMMMMPPPPPPPPFROSXXXXXXEEEEEEXSSSSSXCEEEEEEEBBSSSSSSSSSSSSSFJJJJJJJJJJUUUUUUUUUU
IIITMMMTTTTTTTTTTTTZZZZDDIIIIQIQQQYNNNZNNNNNNNNNKKKUUUUUUUUMMMMMPPPPPPPPFFRRSXXXXXXEEEEEESSSSSXXXXXEEEEEEQSSEEESESSSSSSSRJJJJJJJTNUUNUUUUUUU
IIITTTTTTLTTTTTTTTTZZZZIDIIIIIIQQYYNNNNNNNNNNNNNKKKUUUUUUUUUMMMMPPPPPPPPPSSSSSXXXXXXXXXXXXXSSSXXXXXXEEEEQQQEEEEEESSSSSJSSJJJJJJJTNNNNUUUUUUU
IIIIIIIILLLLTTTTTTTZZZZIIIIIIIIQIAYYNNNNNNNNNNNNNKNUUUUUUUUUMMMPPPPPPPPPPSSSSSSXXXXXXXXXXXXXSXXXXXXXXEEEQQQEEEEEESSSSSSSSJJJJJJJJNANNUUUUUUU
IIIIIIILLLLLZTTTTZZZZZIIIIIIIIIIIAANNNNNNNNNNNNNNNNUUUUUUUUUUMMMPPPPPPPPVVSSSSXDDDDXXXXXXXXXXXXXXXXXEEEEQQQQQEEEYSSSSCSDDDJJJJJJJNNNVVUUUUUU
IIIIIIILLLKLZZZZTZZZZZIIIIIIIIIIIAANNNNNNNNNNNNNNNNUUUUUUUUMMMMMPPPPPPPPPVSSSSXDDDDXXXXXXXXXXXXXXXXHHQCQQQQQQQQQYSSSSSDDDFFJJJJNNNNNVVVVVUUU
IIIIIIILSLKLZZZZTZZZZZZZIIIIIIIIAAANNNNNNNNNNNNNNUUUUUUUUUUUUMMMPPPPPPPPPSSSSSXDDDDXXXXXXXXXXXXXXKKKHQQQQQQQQQQQSSVSDDDDDDJJJJJJNNNNVVVVVVUU
IIIIIIILLLLLZZZZZZZZZZLZLIIIIIIZQAANNNNNNNNNNNNNUUUUUUUUUUUMMMMPPPPPPPPPPPSGGSGDDDDXXXXXXXXXXXXXXKHHHQQQQQQQQQQQQSVDDDDDDDDJRRRNNNNNFVVVVVVV
IIIIIILLLLLLZZZZZLZLLZLLLLIIIIZZZTTTTTNNNNNNNNNUUJUUUUUUUUUUNNMPPPPPPPPPPPSGGGGDDDDXXXXXXXXXXXXXXXHHHHHHQQQQQQQQQVVDDDDDDDRJRRRRNNNLVVVVVVVV
IIIIIILLLLLLLLZZLLLLLLLLLLIIIZZZZTTTTTZNNNNYNNJJUJUJUUUUUUUNNNPPPPPPPPPPPFCCCGGDDDDGXXXXXXXXXXHHHHHHHHHHHHQQQQQQQQQDDDDDDDRRRRNNNNNVVVVVVVVV
RRIPLILLLLLLLLLLLLLLLLLLLLLLIZTTTTTTTTTTZYYYYNJJJJUJJUUUUNNNNNNZPPPPPPPPDDDDDDDDDDDGXXXXXXXXXXXXHHHHHHHHHQQQQQQQQQDDDDDDDDRRRRRNNNRVVVVVVVVV
RRPPLLLLLLLLLZLLLLLLLLLLLLLLIZTTTTZTTTTTZYYYYJJJJJJJNJUUJNNNNNNNRRPPPPCCDDDDDDDDDDDGXCOXXXXXXXXDDHHHHHHHHHQQQQQQQQDDWDDDDRRRRRRRRRRVVVVVVVVV
RPPPLLLLLLLLLZLLLLLLLLLLLLLIIATTTTZTTTTTZZZZYJJJJJJJJJJJJJNNNNNNNRPPPCCCDDDDDDDDDDDGOOOXXXXXXXXXDDHHHHHHHHHQQQQQQQFDWWDDDRRRRRRRRRVVVVVVVVVV
PPPPELLLLLZZZZLLLLLLLLLLLLLLAATTTTZTTTTTTTTPJJJJJJJJJJJJJJJNNNNRRRRPCCCCDDDDDDDDDDDDVOOXXOIOOXXXDDHHHHHHHHQQQQQQQQWWWWVVDRRRRRRRRRRVVVVVVVVV
PWPPPPLLLLLLLZLLLLLLLLLLLLLLAATTTTZZZZTTTTTXXXJJJJJJJJJJJJSNNMMMMRRRRCCCDDDDDDDDDDDDOOOOOOOOOAXXKYHYYYHHHQQQQQQQQQWWWWWWWRRRRRIRRRRVVVVVVVVV
PPPPPYLLLLLLLLLOLLLLLLLLLLLAAATTTTZZZZTTTTTXXXXXJJJJJJJNNJNNNMMMMMRRRRRRDDDDDDDDDDDDOMOOOOOOOAXXKYYYYYYYYQQQQQQHWWWWWWWWWRIIIIIIRZVVVVVVVVVV
PPPPPPPPSSLLLLBBGGLLLLLLLTTTTTTTTTTZZZTTTTTXXXXXJJJJJJJNNNNNNMMMKKMRRRRRDOOOOOOOOODDDDDDDOOOOXXXKKYYYYYYMMQQQQHHWWWWWWWWIIIIITIZZZVVVJVVVVVV
PPPPPPPPPSSLBBBGGGGLLLLLATTTTTTTTTTZZZZZXXXXXXXXXJSJJJJJJJNNNMMMMMMRRRRRDOOOOOOOOODDDDDDDHOOOPPKKKYYYYYYYYQQQQHHHWWWWWWIIIIIIIIWZZZZZVVVVVVV
PPPPPPPPSSBBBBBBBBBBLLLLATTTTTTTTTTZZZZUUXXXXXXXJJJJJWJJJJBNNNNMMMMMRRROOOOOOOOOOODDDDDDDHOPPPPKKKKYYYYYYLQHHHHOHHIIWWIIIIIIIIIIIZZZVVVVVVVV
PPPPPPPPPBBBBBBBBBBAALAAATTTTTTTTTTZZZZZXXXFFFJJJJJJJJJJJJBNNBMMMMMMRRROOOOOOOOOOODDDDDDDOPPPPKKKKAYYYYYLLQHHOOOHHHIIIIIIIIIIIIIIZZZZVVVVVVV
PPPPPPPPPPBBBBBBBBAAAAAANTTTTTTTTTTZUZUXXXYBBFJJBBJJJBBBMMBLLDRRRRRRRRROOOOOOOOOOODDDDDDDIIIIIIIKKAYYKYYYLQAOOOOOOIIIIIIIIIIIIIZZZZZZZVVVVVR
PPPPBBBBPBBBBBBBBBBAAAAANTTTTTTTTTTZUUUXXXYBBBBBBBBJJBBBBBBLLDDRRROOOOOOOOOOOOOOOOOOOOHIIIIIIIIIAAAAYYYYYAAAPPOOOIIIIIIIIIIIIIIIZZZZZZZZVVVR
PPPPPTBBBBBBBBBBBBBAAAANNTTTTTTTTTTZZUUXXUBBBBBBBBBBBBBBBBDDDDDRDROOOOOOOOOOOOOOOOOAOOHIIIIIIIAAAAAAAAAAYAAAAAWWOWIIIIIIIIIIIOOIZZZNZZZZVVRR
PPPPPPBBBBBBBBBBBBAAAANNNNNNNNNNNNZZZUUUUUBBBMBBBBBBBBBBBBDDDDDDDROOOOOOOOOOOOPOOOOOOOHIIIIIIAACCCAAAAAAAAAAAAWWWWWBIIIIIIIIIOOUUZZZZZRZRRRR
PPPPPBBBBBBBBBBBBAAAANNNNNNNNNNNNNNUUUUUUUUBBMMBBBBBBBBBBBDOOOOOOOOOOOOOOOOOOOPOPOOOOOOIIIICICACUUUUAAAAAAAAAAWWWEWBIIIIIIIIIIUUUZUUZRRRRRRR
VPPPBBBBBBBBBBBBAAAAAARRRRRNNNNNNNNUUUUUUUUUMMMMBBBBBBBBDDDOOOOOOOOOOOOOOOOOOOPPPPOOOIIIIICCCCCCCUUUUAAAAAAAWWWWWEWBIIIIIIUIIIUUUUUUUURRRRRR
VPVPUBBBBBBBBBBBBAARRRRRRRRRNNNNNNNUUUUUUUUMAAMMBBBBBBDDDDDOOOOOOOOOOOOOOOOOPPPPPPOOOOIIIIICCCCCUUUMUUUAAAAVWWWEWEEIIIIITUUUUUUUUUUUUURRRRRR
VVVVBBBBBBBDDDYBAAARRRRRRRRRNUNNUUUUUUUUUUUMMMMMBBBBBBBDDDDOOOOOOOOORKKKKRRPPPPPPLPPOOIIIIICCCCCCCUUUUUAAWSSSSSEEEEEEEEETTTUUUUUUUUUUURRRRRR
VVVVBBBBBBDDDDDBOAARRRRRRRRRUUUUUUUUUUUUUUMMMMMMBBBBBBBDDDDDDDKNDRRRRKKKKKRRRPPPPLPPIIIIIIICCCCCCCUUUUUUUUSSSSSSEEEEEEETTTTEUUUUUUUUUURRRRRR
VVVVVVVNDDDDDDDDOOOORRRRRRRRRUUUUUUUUUUUUUUUMZXXBBBBBHBDDDDDDHKKKKKKKKKKKKRRRRPPPPPPIIIIIIICCCCCCUUUUUUUUUSSSSSSSSSEEETTTTTUUUUUUDDUUURRRRRR
VVVVVVVDDDDDDDDDOOOORRRRRRRUUUUUUUUUUUUUUUUUZZZBBBBBBBDDDDDDDDKJJKKKKKKKKKKKKKPPPPPPIIIIIICCCCCCCUUUUUUUNNSSSSSSSMMEMETTTTTTUUQQDDDDQUURRRRR
VVVVVVVVDDDDDDOOOOOORRRRRRUUUUUUUUUUUUUUUUUUUZZBBBUUUUDDDDDDDKKJJKKKKKQKKKKKKGPPPPPPPIIIIIIICCCCCUUUUUUUNSSSSSSSSMMEMEETTTTTUUQQQQDDQQQPPPPP
VVVVVVVHHDDDDDDOOOOOORRRRRRRJUUUUUUUUUUUUUUZZZZZXBZZZDDDDDDDDJJJJJKKKKKKKKKKKGFPVPPPPIIIIICCCCCQCUUUUUUUUTUSSSSSMMMMMMETTTTTUQQQQQDDQQQPPPPP
VVVVVVHHHDDDDDDOOOOOOORRRRRRJUSJUUJUUUUUHUZZZZZZXZZAAADDDDGGDJJJJKKKKKKKKKKKKKFPPFPPIIIIIIIIIIIIUUUUUUUUUUUUSSSSSSMMMUCCTCTTTTQAQQQQQQQPPPPZ
VVVVVVHHHDSDDOOOOOOOOORRRRRRJUSJJJJZUZZUZZZZZZZZZZZAADDDDDGGDJJJJKKKKKKKIKKFFFFPFFIIIIIIIIIIIIIUUUUUUUUUUUUUSSSSSSMUUUCCCCCCCCAAAQQQQQQQPPPP
VVVVVVHHNNNODOOOOOOOOORRRRRRJJJJJJAZZZZZZZZZZZZZZZDDDDDDDDGGGJJJKKKKKKKKKKKFFFFFFFIFIIIIIIIIIIIIUUUUUUUUUYUNSSSSSSMSUUCCCCCCCCAAAAAAAAQQQQQQ
VVNNNVHHNNNOOOOOOOOOOOOJAARJJJJGJJJZZZZZZZZZZPPPZZDDDDDDDDDGGJJJCCKKKKKKKKFFFFFFFFFFFIIIIIIIIIIUUUUUUUUUUUNNSSSSSSSSSCCCCCCCAAAAAAAAAAAQQQQQ
VVNNNNNNNNNOOOOOOOOOOOOJJJJJJJJJJJJZZZZZZZZZZPPPZZZDDDDDDDDDDDDCCCCKKKKKCFFFFFFFFFFFGGIIIIIIIIIUUUUNNUNNNNNSSSSSSSSSSSCCCCCCAAAAAAAAAAQQQQQQ
TTTNNNNNNNNOOOOOOOOOOOOJJJJJJJJJJJJZZZZZZZZPPPPPPPZDDDDDDDDDDDDDCCKKKKKCCCFFFFFFFFTFRRRRRIIIIAAAXUUNNNNNNNSSSSSSSSSSSZCCCCCCAAAAAAAAAZEQQQQQ
TNNNNNNNNNNNNOOOOOOOOOOJJJJJJJJJJJJZZZZZZZZPPPPPPPPDDDDDDDDDDDDCCCKCCCCCCCCCFFFFFFRRRRRRRRIIIAAAUUUUNNNNNISSSSSSSSSSZZCVCCCCAAAAAAAAAZZQQQQQ
TNNNNNNNNNNNNOOOOOOOOOOJJJJJJJJJJJJJJZZZZPPPPPPPPPPDDDDDDDDDDDDDCCCCCCCCCCCCFFFXFFIIRRRRRRAIIAAAFFUNNNIINISSSSSSSSSSSSSSCCCCCAAAAAAAZZZZQQQQ
TNNNNNNNNNNNOOOPOOOOOOOLJJJJJJJJJJJJJZZZZPPPPPPPPPPDHDDDDDDDDYDDDCCCCCCCCCCCXSFXXXXIRRRRRRAAAAAAAANNNIIIIIISSSSSSSSSSSSSSSSCOAAAAAAAZZAZQQQQ
NNNNNNNNNNNUUOPPPPPPOOOJJJJJJJJJJJJJZZZTTTPPPPPPPPPPHDDDDDDDDYDDDDCCCCCCCCCXXXXXXXXXRRRRRRRRAAAAAANNNIIIIIISSISSSSSSSSSSSSSSOAAAAAAAAAAAQQQQ
NNNNNNNNNNNUUPPPPPPPPOOJYYJJJJJJJJJJZZZTTTTTTTTTPPNNDDDDDDDDDDDDDCCCCCCCCCCXXXXXXXXXXXRRRRRAAAAAAANNNIIIIIIIIISSSSSSSSSSSSRRAAAAAAFFAAAAAQQQ
NNNNNNUNNNPUUUUPPPPPPPPPJJJJJJJJJJJJZZZTTTTTTTTTPPPNNDDDDDDDDDDDDCCCCCCCCCCXXXXXXXXXXXRRRRRAAAAAANNNNIIIIIIIIISSSSSSFFRRSRRRAAAEFFFFAAAAAAQQ
NNNNNNUUPPPUUUPPPPPPPPPBIBJJJJJJTTTTTTTTTTTTTTTTPPPNNNYDDDDDDDDDDCCCCCCCCCCCXXXXXXXXXXRRRRRAAARJNNNNNIIIIIIIISSSSSSSFFRRRRRRRREEFFFFTAFFVRQQ
NCNNNNUUPPPPUUUPPPPPPPBBBBCJBJJJTTTTTTTTTTTTTTTTPPPPYNYYDVDDDDDDDDCCCCCCCCCCXXXXXXXXXXRRRRRRRRRJJJNJJIIIIIIIISSSFFFFFFFFRRRRRRREFFFFFFFFRRRR
CCCNUNUUPPPPUUPPPPPPBPBBBBBBBJBBTTTTTTTTTTTTTTTTPPPYYYYYVVDDDDDDDDCCCCCCCCCCBXXXXXXXRRRRRRRRRRRJJJJJJJIIIISSSSSSFFFFFRRRRRRRRXFFFFFFFFFFRRRR
CCCCUUUUPPPPUUBPPPPPBBBBBBBBBBBBTTTTTTTTTTTTTTTTPPPYYYYYDDDDDDDEDCCCCCCCCCKKKKKKKKKKRRRRRRRRJJJJJJJJJJIJJJJSSSSSFFFFFRRRRRRRRXFFFFFFFGFRRRRR
CCCUUUUUUPPPPUUPPPPPTTTBBBBBBBBBTTTTTTTTTTTTTTTTPPPYYYYYDDDDDDDDDCCCRCCCCCKKKKKKKKKKKKKKKKKKKJJJJJJJJJJJJJOSJSSSFFFFFFRRRRRRRRRFFFFFRGRRRRRR
CCCUUUUUPPUUPUIPPPPPTTBBBBBBBBBYTTTTTTTTTTTTTTTTBBPPPYYYYYDDDDDDDCCCCCCCCCKKKKKKKKKKKKKKKKKKKJJJJJJJJJJJJJJJJSSSFFFFRRRRRRRRRRRQQFQQRRRRRRRR
CCUUUUUUUUUUUNGGTPPPTTBBBBBBBBBYTTTTTTTTTTTTTTTTGBGYYYYYYYYDDDDDDDCCCCCCBCKKKKKKKKKKKKKKKKKKKJJJJJJJJJJJJJJJJSSFFFFFRRRRRRRRRRRQQFQQRRRRRRRR
UUUUUUUUUUUUUGGGTPTTTTTBBBBBBBBBYYYYTTTTTTGGGGGGGGGGGYYYYYYDDDDDDNCCCCCCBBKKKKKKKKKKKKKKKKKKKJJJJJJJJJJJJJJJJJFFJFFFRRRRRRRRRRQQQQQQQRRRRRRR
UUUUUUUUUUUUUGGGTTTTSTBBBBBBBBBYYYYYTTTTTTGGGGGGGGGGGYYYYYYYDGDDDDFCCCCBBBKKKKKKKKKKKKKKKKKKKJJJJJJJJJJJJYJJJJJJJFRRRRRRRRHWRRRQQQQQQRRRRRRR
UUUUUUUUUGUUGGGGGGGSSTSSBBBBBBBBYYYYYYYYYWGGGGGGGGGGYYYYYYYGGGGGGGFCCCCBBBKKKKKKKKKKKKKKKKKKKJJJJJJJJJJJYYJJJJJJJJJRRRRRFRHWWWWQQQQQQRRRRRRR
UUUUUUUUUUAUGGGGGGSSSSSSSBBBBBBYYYYYYYYYWWGGGGGGGGGYYYYYYYYGGGFGFFFFFCBBBBKKKKKKKKKKKKKKKKKKKUJJJJJJJJJJYYJJJJJJJJJJRRRRRWWWWWWWQQQQQRLLRRRR
GUUUUUUUUUGGGGGGGGSSSSSSSSBBBBBYYYYYYYWYWWWGGGGGGGPPGJYYYYYYFFFFFFFFFFFFBBBBBBBBBBBKKKKKKKKKKUJJJJJJJYYYYYYJJZJJJJJJJRJRBWWWWWWWWWTQQLLLLRRR
GUUUUUUUUUUGGGGGGGGSSSSSSSSRYYYYYYYYYYWWWWWWGGGGGGGPGGYYYYYFFFFFFIFFFFFBBBBBBBBBBBCKKKKKKKKKKUUJJJJJYYYYYYYJJZJJJJJJJJJWWWWWWWWWWWQQQLLLLLLR
GGGUUUUUUUGGBBBCCBBSSSSSSSSRYYYYYYYMMWWWWWWWGGGGGGGGGYYYYYYFFFFFFFFFFFFFFFBBBBMMBBCKKKKKKKKKKUUUJJJJJJJYYZZZDZZJJJJJJJWWJWMWWWWWWWLLLLLLLLLL
GGGGUUUUGGGGBBCCCBBPPSSSSSSSSSOOMMYMWWWKKWWWGGGGGGGGEEEEYYYDFDDFFFFFFFFFFFBBBBBMBBCCCKKKKKKKKUUUJPPJJYYYYYZZZZJJJJJJJJJWJWWWWWWFWWWLLLLLLLLL
GGGGGUUUGGGGBBBCBBBBBBRSSSSSSBMMMMMMMWWKKKKWGGGGGGGEEEEEYYYDEDMMMFFJJFFCMMBBBMMMCCCCHCUUUUUUUUUUUUPPPPPYYYYZZZZZJJJJJJJJJJWCWWWWWLLLLLLLLXLX
PGGGGGGGGBBBBBBBBBBBBBBSSSSSSBBBMMMMMWKKKKKKGGGGGGGGEEEEEDRDDDMDDDDJJJJJMMMMMMMMMCMCHCUUUUUUUUUUUUPEPEYYYYYZZZZJJJJJJJJJJJWCCWWWWTTLLLLLXXXX
PGGGGGGDGGBBBBBBBBBBBBBIISSSSSBBMMMMMKKKKKKKKKGGGGGBBBBEBDDDDDDDDDDJJJJMMMMMMMMMMMMHHCUUUUUUUUUUUUPEEEEYYYYZZZZJJJJJJJJJJJCCCWWWWTTLLXXLXXXX
PPPGGDDDDBBBBBBBBBBBBNBISSSSSSBBBMMMMKKKKKKKKKKGGLBBBBBBBDDDDDDDDDDJJJJMMMMMMMMMMHHHHHHHHHUUUUUUUPPPEEEEEYZZZZZJJJJJJJCCCJCCCWWCCTTTLLXXXXXX
PPPGGDDDDDDBBBBBBBBNNNBBSSSSSSSBBBMMMMKKKKKKKKGGABBBBBBBBDDDDDDDDJJJJJJJJMMMMMMMMMHHHHHHHHHUUUUUUUPEEEEECZZZZZZZZJJJJCCRCCCCCCCCTTTTLLLXXXXX
PPPPGDDDDDBBBBBBBBBNNNNNNMSSSSSSBBMBBBBKKKKKKKKKKKBBBBBBBBBYDDDDDJJJJJJYYYYMMMMMMMHHHHHHHHHUEEUUUZEEEEEECZZZZZZZZZJJJCCCCCCCCTTTTTTTLXXXXXXX
PPPBPRDDDDKBBBBBBBBBNNNNMMSSSSSBBBBBBBBKKKKKKKKKKKBBBBBBBBBDDDDDDJJEEEEYYYYMMMMMMMHHHHHHHHUUEEEEEEEEEEEZZPZZZZZZZZJJAECCCCCCCHHHTTTTWXWXXXXX
PPPPPRRDDVBBBBBBBMMMMNNNMMMSSSZZBBBBBBBKKKKKKKKKKBBBBBBBBBBDDDDDDJEEEEEEEEYMAMMMMMMMMHPHHHUUUEEEEEEEEEEZZZZZZZZZZZZJAACCCCCHHHHTTTTTWWWWWWWX
PPPPPPPPVVVBBBBBBNNMMMMMMSSSZZZZZBBBBBKKKKKKKKKKKBBBBBBBBBBBDDDDDJJEEEEEEEEMAMMMMMMMMMMMMHHUUEEEEEEEEEZZZZZZZZZZZZZAAAACCCCCHHHTTTTTMWWWWWWX
PPPPPPPPPVVBBBBBBMMMMMMMMMMZZZZZZZZZBBKKKKKKKKKKBBBBBBBBBBBBDGDQEEEEEEEEEEEEEOMMMMMMMMUCUUUUUUEEEEEEEEEZZZZZZZZZZZZBAAAAACCCCAHHHHWMMWWWWWWX
PPPPPPPPNDDDBBBBMUMMMMMMMMMMMZZZZZZBBZKKKKKKKKKKBBBBBBBBBBBLDBUEEEEEEEEEEDDDDDDDDDDDDMUUUUUUUEEEEEEEEEEZZZZZZZZZZZAAAAAAAACAZAHHHWWWWWWWWWWW
PPPPPPPPDDDDGBBBMMMMMMMMMMMMMMZZZZZZZZKKKKKKKKKKBBBBBBBBBBBBBBBEEEEEEEEEEDDDDDDDDDDDDJUYUUUUUEEEEEEEZZZZZZZZZZZZWWAAAAAAAAAAAAAAWWWWWWWWWWWW
PPPPDDDDDDDGGBBMMMMMMMMMMMMMMMZZZZZZZZZZKKDKKKKKBBIBIIBBBBBBBQEEEEEEEEEEEDDDDDDDDDDDDJJYUUUUUEEEEEEEZHZZZZZZZZZZZAAAAAAAAAAAAAAAWWWWWWWWWWWW
PDDDDDDDDDDDDDDFFMMMMMMMMMMMMZZZZZZZZZZZKKKKKKKDDIIIIIIBBBBBBBEEEPPEEEEEEEEEEEEDDDDDDYYYUUUUUUEEEEEEZZZZZZZZZZZZZAAAAAAAAAAAAAAAGWWWWWWWWWWW
PDDDDDDDDDDDDFFFFMMAAAMMMMPMZZZZZZZZZZSZZWKDDDDDDIIIIIIIIBBBBBHEEPPPEEEEEEEEEEEDDDDDDYYYUUUUUEEEEEEEZZZZZHHHHHHHHHHAAAAAAAAAAAAAWWWWWWWWWWWW
DDDDDDDDDDDDDFFFFFFAAAMMMMMMZZZZZZZZZZZZZZZZDDDDDIIIIIIIIIBBLBPPVPPPEPEEEEEEEEEDDDDDDYYYYYUUUUUHEEEEZZZZZHHHHHHHHHHHAAAAAAAAAAAAWWWWWWWWWWWW
DDDDDDDDDDDDXXFFFFFAAAMMMMMMZZZZZZZZZZZZZZDDDDDDDIIIIIIIIILLLPPPPPPPEPPPPEEEEEEDDDDDDYYYYYUUUHHHHHZZZZZZZHHHHHHHHHVVVAAAAAAAAAAAWWWWWWWWWWWW
DDDDDDDDDDDSXXFFFFFAAAMMMAZZZZZZZZZZZZZZOZIIDZZZZZIIIIIIIILLLPPPPPPPPPPPPPPPEELDDDDDDYYYYYUUUHHHHHZZZZZZZHHHHHHGHVVAAAAAAAAAAAAAAWWWWWWWWWWW
DDDDDDDDDDXXXXFFFFAAAAAMAAAZZZZZZZZZZZZZOOIIDDZZIIIIIIIIIILLLPPPPPPPPPPPPPPPGLLLGDDDDYYYYYUHHHHHHHZZZZZHHHHHHHHHHVVVAAAAAAAAAWWAFWWWWWWWWWWW
DDDDDDDDDDDXXXFFFAAAAAAAAAAZZZZZZZZZZRRIIIIIIIZZZZIIIIIIIILLZPPPPPPPPPPPPPGGGGLLGDDDDYYYYYUUUUUHHHZZZZZHIHHHHHVVVVVAAAAAAAAAAAAFFWWWWWWWQWQW
DDDDDDDDDDDXXFFFFAAAAAAAAAAAAAAZZZZZZIIIIIIIIIIIZZIZIIIIIILZZZPPPPPPPPPPJPGGJGLGGGGGYYYYYYUUUUUIIIPIIIHHIIHHHVVVVVUUUUAAAFAAAFFFFWWWWWWQQQQQ
NDDDDDDDDDDXXFFFFAAAAAAAAAAAAAAZZZZIIIIIIIIIIIIIIZIZZIIIIIZZZXPPPPPPPPPJJPDGGGGGGGGGNGYYYYYUUUUUIIIIIIHHIIIIHVVVVUUUUUUUAFAAAFFFFFFWQWQQQQQQ
DDDDDDFDDFFFXFFFAAAAAAAAAAAAAAAXZXZZIIIIIIIIIIIIZZZZZIIIIZZZZPPPPPPPPPPPPPGGGGGGGGGGGGYYYYYUUJJUIIIIIIIIIIIVVVVVUUUUUUUUAFFFFFFFFFQQQQQQQQQQ
VVDDDDDFFFFFXFFFFAAAAAAAAAAAAXXXXXXZIIIIIIIIIIIIIZZZZZZZZZZZZPPPPPPPPPPDGGGGGGGGGGGGGGYYYYYUJJJJJJIIIIIIIIIIIIVVUUUUUUUUUUUFFFFFFFFQQQQQFFQQ
VVDDDFFFFFFFFFFFFAAAAAAAAAAAXXXXXXIIIIIIIIIIIIIIZZZZZZZZZZZZZPPPPPPPPPPPDGGGGGGGGGGGGGGGYYYUUUJJJJIIIIIIIIIIIVVVUUUUUUUUUUUUFFFFFFFQQQFFFFFQ
VVFFFFFFFFFFFFFFFAAAAAAAAAAAXXXXXXIPIIIIIIIIIIZZZZZZZZZZZZZZZDDDDDDPPPPDDDGGGGGGGGGGGGGGYYYYYJJJJIIIIIIIIIIIVVUUUUUUUUUUUUUUUFFFFFFQFFFFFFFF
FVFFFFFFFFFFFFFFFAAAAAAAAAAXXXXXXXIIIIIIIIIIIIZZZZZZZZZZZZZZZDDDDDDDPDDDDGGGGGGGGGGGGGGGYYYYJJJJJJJIIIIIIIIIVUUUUUUUUUUUUUUUUFFFFFFFFFFFFFFF
FFFFFFFFFFFFFFFFFFAAAAATTAXXXXXXIIIIIIIIIIIIIIIZZZZZZZZZZZZZZDDDDDDDDDDDDDGGGGGGGGGGGGGGJJJJJJJJJJJJIIIIIIIIVVVUUUUUUUUUUUUUFFFFFFFFFFFFFFFF";
const string inputTest = @"RRRRIICCFF
RRRRIICCCF
VVRRRCCFFF
VVRCCCJFFF
VVVVCJJCFE
VVIVCCJJEE
VVIIICJJEE
MIIIIIJJEE
MIIISIJEEE
MMMISSJEEE";

const string inputTest2 = @"AAAA
BBCD
BBCC
EEEC";
const string inputTest3 = @"EEEEE
EXXXX
EEEEE
EXXXX
EEEEE";

const string inputTest4 = @"AAAAAA
AAABBA
AAABBA
ABBAAA
ABBAAA
AAAAAA";

void Part1(string input)
{
    var grid = input.Split(Environment.NewLine).Select(l => l.ToCharArray()).ToArray();
    var maxX = grid.Length;
    var maxY = grid[0].Length;
    
    bool InBounds(int x, int y) => x >= 0 && x < maxX && y >= 0 && y < maxY;

    var disjoints = new DisjointSet<(int x, int y)>();
    for (int x = 0; x < maxX; x++) {
        for (int y = 0; y < maxY; y++) {
            disjoints.MakeSet((x,y));
        }
    }
    void TryUnion( int x, int y, int x2, int y2) {
        if(InBounds(x2, y2) && grid[x][y] == grid[x2][y2]) {
            disjoints.Union((x,y), (x2,y2));
        }
    }
    for (int x = 0; x < maxX; x++) {
        for (int y = 0; y < maxY; y++) {
           //TryUnion(x,y, x-1, y);
            //TryUnion(x,y, x, y-1);
            TryUnion(x,y, x+1, y);
            TryUnion(x,y, x, y+1);
        }
    }
    
    long sum = 0;
    foreach( var group in disjoints.GetSets()) {
        long area = group.Count();
        long perimeter = 0;
        foreach (var entry in group) {
            if ( !group.Contains((entry.x - 1, entry.y))) {
                perimeter++;
            }
            if (!group.Contains((entry.x + 1, entry.y))) {
                perimeter++;
            }
            if (!group.Contains((entry.x, entry.y - 1))) {
                perimeter++;
            }
            if (!group.Contains((entry.x, entry.y + 1))) {
                perimeter++;
            }
            
        }

        var groupKey = group.First();
        Console.WriteLine($"Group { grid[groupKey.x][groupKey.y] -- }Area: {area} Perimeter: {perimeter}");
        sum+= area * perimeter;
        
    }
    Console.WriteLine(sum);

}

void Part2(string input)
{
    var grid = input.Split(Environment.NewLine).Select(l => l.ToCharArray()).ToArray();
    var maxX = grid.Length;
    var maxY = grid[0].Length;
    
    bool InBounds(int x, int y) => x >= 0 && x < maxX && y >= 0 && y < maxY;

    var disjoints = new DisjointSet<(int x, int y)>();
    for (int x = 0; x < maxX; x++) {
        for (int y = 0; y < maxY; y++) {
            disjoints.MakeSet((x,y));
        }
    }
    void TryUnion( int x, int y, int x2, int y2) {
        if(InBounds(x2, y2) && grid[x][y] == grid[x2][y2]) {
            disjoints.Union((x,y), (x2,y2));
        }
    }
    for (int x = 0; x < maxX; x++) {
        for (int y = 0; y < maxY; y++) {
            //TryUnion(x,y, x-1, y);
            //TryUnion(x,y, x, y-1);
            TryUnion(x,y, x+1, y);
            TryUnion(x,y, x, y+1);
        }
    }
    
    long sum = 0;
    foreach( var group in disjoints.GetSets()) {
        long area = group.Count();
        var groupKey = group.First();
        var groupChar = grid[groupKey.x][groupKey.y];
        long perimeter = 0;
        var fencesUp = new HashSet<(int x, int y)>();
        var fencesDown = new HashSet<(int x, int y)>();
        var fencesLeft = new HashSet<(int x, int y)>();
        var fencesRight = new HashSet<(int x, int y)>();
        foreach (var entry in group) {
            if ( !group.Contains((entry.x - 1, entry.y))) {
                fencesUp.Add((entry.x, entry.y));
                perimeter++;
            }
            if (!group.Contains((entry.x + 1, entry.y))) {
                fencesDown.Add((entry.x, entry.y));
                perimeter++;
            }
            if (!group.Contains((entry.x, entry.y - 1))) {
                fencesLeft.Add((entry.x, entry.y));
                perimeter++;
            }
            if (!group.Contains((entry.x, entry.y + 1))) {
                fencesRight.Add((entry.x, entry.y));
                perimeter++;
            }
        }

        int HorizontallyAligned(HashSet<(int x, int y)> set) {
            var alignedHorizontally = new DisjointSet<(int x, int y)>();
            foreach (var fence in set) {
                alignedHorizontally.MakeSet(fence);
            }
            foreach (var fence in set) {
                if( set.Contains((fence.x, fence.y - 1))) {
                    alignedHorizontally.Union(fence, (fence.x, fence.y - 1));
                }

                if (set.Contains((fence.x, fence.y + 1))) {
                    alignedHorizontally.Union(fence, (fence.x, fence.y + 1));
                }
            }
            return alignedHorizontally.GetSets().Count();
        }

        int VerticallyAligned(HashSet<(int x, int y)> set)
        {
            var alignedVertically = new DisjointSet<(int x, int y)>();
            foreach (var fence in set) {
                alignedVertically.MakeSet(fence);
            }
            foreach (var fence in set) {
                if( set.Contains((fence.x - 1, fence.y))) {
                    alignedVertically.Union(fence, (fence.x - 1, fence.y));
                }

                if (set.Contains((fence.x + 1, fence.y))) {
                    alignedVertically.Union(fence, (fence.x + 1, fence.y));
                }
            }
            return alignedVertically.GetSets().Count();
        }


        var alignedUp = HorizontallyAligned(fencesUp);
        var alignedDown = HorizontallyAligned(fencesDown);
        var alignedLeft = VerticallyAligned(fencesLeft);
        var alignedRight = VerticallyAligned(fencesRight);
        var contiguousFencesCount = alignedUp + alignedDown + alignedLeft + alignedRight;

        Console.WriteLine($"Group { groupChar } -- Area: {area} Perimeter: {perimeter} Contiguous Fences: {contiguousFencesCount}");
        sum+= area * contiguousFencesCount;
        
    }
    Console.WriteLine(sum);

}


Part2(inputReal);